<?php

declare(strict_types=1);

namespace App\Http\Controllers\BusinessAdmin;

use App\Http\Controllers\Controller;
use App\Models\InventoryStocktake;
use App\Services\BusinessAdmin\InventoryStocktakeService;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

final class StocktakeController extends Controller
{
    public function __construct(private readonly InventoryStocktakeService $stocktakes) {}

    public function index(Request $request): View
    {
        return view('business-admin.stocktake.index', [
            'stocktakes' => $this->stocktakes->listForAdmin($request->user(), $request->input('status')),
        ]);
    }

    public function show(Request $request, InventoryStocktake $stocktake): View
    {
        abort_unless((int) $stocktake->organization_id === (int) $request->user()->organization_id, 403);

        return view('business-admin.stocktake.show', [
            'stocktake' => $stocktake->load(['items.item.category', 'items.supplier', 'branch', 'creator']),
        ]);
    }

    public function review(Request $request, InventoryStocktake $stocktake): RedirectResponse
    {
        $this->stocktakes->startReview($request->user(), $stocktake);

        return back()->with('status', 'Stocktake moved to review.');
    }

    public function approve(Request $request, InventoryStocktake $stocktake): RedirectResponse
    {
        $data = $request->validate([
            'adjustments' => ['nullable', 'array'],
            'adjustments.*.inventory_stocktake_item_id' => ['required', 'integer'],
            'adjustments.*.ordered_qty' => ['nullable', 'numeric', 'min:0'],
            'adjustments.*.excluded_from_order' => ['sometimes', 'boolean'],
            'adjustments.*.override_reason' => ['nullable', 'string', 'max:500'],
        ]);

        $this->stocktakes->approve($request->user(), $stocktake, $data['adjustments'] ?? []);

        return redirect()
            ->route('business-admin.stocktake.show', $stocktake)
            ->with('status', 'Stocktake approved. Purchase orders generated by vendor.');
    }

    public function reject(Request $request, InventoryStocktake $stocktake): RedirectResponse
    {
        $validated = $request->validate(['reason' => ['nullable', 'string', 'max:500']]);
        $this->stocktakes->reject($request->user(), $stocktake, $validated['reason'] ?? null);

        return back()->with('status', 'Stocktake rejected.');
    }

    public function reopen(Request $request, InventoryStocktake $stocktake): RedirectResponse
    {
        $this->stocktakes->reopen($request->user(), $stocktake);

        return back()->with('status', 'Stocktake reopened.');
    }

    public function print(Request $request, InventoryStocktake $stocktake): View
    {
        abort_unless((int) $stocktake->organization_id === (int) $request->user()->organization_id, 403);

        return view('business-admin.stocktake.print', [
            'stocktake' => $stocktake->load(['items.item.category', 'branch', 'creator']),
        ]);
    }
}
